// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycvitscifpsbtcfhkdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y3ZpdHNjaWZwc2J0Y2Zoa2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDI2MDksImV4cCI6MjA3NDExODYwOX0.Ol2CaFBddvYAJqcDRFVOOSFX0wmaJOQcVx2Ojzt7Z40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});